// Generated by scripts/generate-i18n-messages.mjs. Do not edit directly.
import { SPANISH_FOUNDATION_MESSAGES } from "./messages-foundation";
import { SPANISH_EVIDENCE_MESSAGES } from "./messages-evidence";

export type AtlasLocale = "en" | "es";

export const SPANISH_UI_MESSAGES: Readonly<Record<string, string>> = {
  ...SPANISH_FOUNDATION_MESSAGES,
  ...SPANISH_EVIDENCE_MESSAGES,
};
