import type {
  ComponentGraph,
  ComponentNode,
  ComponentPlaygroundContract,
  ComponentProp,
  DesignToken,
  PreviewControl,
  PreviewControlPreset,
  PreviewDependencyEnvironment,
  PreviewScenario,
  PreviewStyleEnvironment,
} from "./types.js";

function titleCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .replace(/\b\w/g, (character) => character.toUpperCase());
}

function unionOptions(type: string): string[] {
  const options = type
    .split("|")
    .map((candidate) => candidate.trim().replace(/^\((.*)\)$/, "$1"))
    .flatMap((candidate) => {
      const quoted = candidate.match(/^["']([^"']+)["']$/);
      if (quoted?.[1] !== undefined) return [quoted[1]];
      if (/^-?\d+(?:\.\d+)?$/.test(candidate)) return [candidate];
      if (/^(?:true|false|null)$/.test(candidate)) return [candidate];
      return [];
    });
  return [...new Set(options)];
}

function optionValue(option: string): unknown {
  if (option === "true") return true;
  if (option === "false") return false;
  if (option === "null") return null;
  if (/^-?\d+(?:\.\d+)?$/.test(option)) return Number(option);
  return option;
}

function semanticOptions(prop: ComponentProp): string[] {
  const name = prop.name.toLowerCase();
  if (/^(to|href|url)$/.test(name)) return ["", "/", "/search"];
  if (/size$/.test(name)) return ["xs", "sm", "md", "lg"];
  if (/position$/.test(name)) return ["static", "top-left", "top-right"];
  if (/align(?:ment)?$/.test(name)) return ["left", "center", "right"];
  if (/orientation$|direction$/.test(name)) return ["horizontal", "vertical"];
  return [];
}

function semanticSample(name: string): unknown {
  const normalized = name.toLowerCase();
  if (normalized.includes("genre")) {
    return { mal_id: 1, name: "Action", type: "Anime" };
  }
  if (normalized.includes("anime")) {
    const poster =
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='600' height='900'%3E%3Cdefs%3E%3ClinearGradient id='g' x2='1' y2='1'%3E%3Cstop stop-color='%231b2540'/%3E%3Cstop offset='1' stop-color='%23516ba8'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='600' height='900' fill='url(%23g)'/%3E%3Ccircle cx='430' cy='250' r='150' fill='%2378dce8' fill-opacity='.22'/%3E%3Cpath d='M90 690L260 430l110 155 70-85 90 190z' fill='%23f4f7fb' fill-opacity='.72'/%3E%3Ctext x='54' y='810' fill='%23f4f7fb' font-family='sans-serif' font-size='48' font-weight='700'%3EATLAS SAMPLE%3C/text%3E%3C/svg%3E";
    const image = {
      image_url: poster,
      small_image_url: poster,
      large_image_url: poster,
    };
    return {
      mal_id: 1,
      url: "#",
      images: { jpg: image, webp: image },
      trailer: {
        youtube_id: null,
        url: null,
        embed_url: null,
        images: {
          image_url: null,
          small_image_url: null,
          medium_image_url: null,
          large_image_url: null,
          maximum_image_url: null,
        },
      },
      approved: true,
      titles: [{ type: "Default", title: "Sample anime" }],
      title: "Sample anime",
      title_english: "Sample anime",
      title_japanese: null,
      title_synonyms: [],
      type: "TV",
      source: "Manga",
      score: 8.4,
      scored_by: 42000,
      rank: 42,
      popularity: 120,
      members: 180000,
      favorites: 12000,
      episodes: 12,
      year: 2026,
      status: "Currently Airing",
      airing: true,
      aired: { from: "2026-01-01", to: null, string: "Jan 2026 to ?" },
      duration: "24 min per ep",
      rating: "PG-13",
      synopsis: "A deterministic sample generated by Component Atlas.",
      background: null,
      season: "winter",
      genres: [{ mal_id: 1, name: "Action", type: "Anime", url: "#" }],
      themes: [],
      demographics: [],
      studios: [{ mal_id: 1, name: "Atlas Studio", type: "Anime", url: "#" }],
      addedAt: 0,
    };
  }
  if (normalized.includes("user")) {
    return { id: "atlas-user", name: "Atlas User", avatarUrl: "" };
  }
  if (normalized.includes("item")) {
    return { id: "atlas-item", name: "Sample item", label: "Sample item" };
  }
  return { id: "atlas-sample", name: "Sample value", label: "Sample value" };
}

function complexPresets(prop: ComponentProp): PreviewControlPreset[] {
  const isArray = /\[\]|Array\s*</.test(prop.type);
  const namedReferences = prop.type
    .split("|")
    .map((candidate) => candidate.trim())
    .filter((candidate) => !/^(?:null|undefined)$/.test(candidate));
  const isObject =
    isArray ||
    /\b(?:object|Record|Map|Set)\b/.test(prop.type) ||
    (namedReferences.length > 0 &&
      namedReferences.every((candidate) =>
        /^[A-Z][A-Za-z0-9]*(?:<.*>)?$/.test(candidate),
      )) ||
    /^[A-Z][A-Za-z0-9]*(?:<.*>)?(?:\s*\|\s*(?:null|undefined))?$/.test(
      prop.type,
    );
  if (!isObject) return [];
  const sample = semanticSample(prop.name);
  const samplePreset = {
    label: isArray ? "Sample list" : "Sample data",
    value: isArray ? [sample] : sample,
  };
  const emptyPreset = {
    label: isArray ? "Empty list" : "Empty object",
    value: isArray ? [] : {},
  };
  return prop.required
    ? [samplePreset, emptyPreset]
    : [{ label: "Not set", value: null }, emptyPreset, samplePreset];
}

function isAction(prop: ComponentProp): boolean {
  return (
    /^on[A-Z]/.test(prop.name) ||
    /=>|\bFunction\b|\(\s*\)\s*=>/.test(prop.type)
  );
}

function defaultText(name: string): string {
  const normalized = name.toLowerCase();
  if (normalized === "classname" || normalized.endsWith("classname")) return "";
  if (normalized.includes("title") || normalized.includes("heading")) {
    return "A component worth reusing";
  }
  if (normalized.includes("description") || normalized.includes("message")) {
    return "Explore this state, adjust its contract, and save the result.";
  }
  if (normalized.includes("label")) return "Example label";
  if (normalized.includes("name")) return "Atlas specimen";
  if (normalized.includes("children") || normalized.includes("content")) {
    return "Preview content";
  }
  if (normalized.includes("url") || normalized.includes("href")) return "#";
  if (normalized.includes("poster") || normalized.includes("image")) return "";
  return "";
}

function parseDefault(prop: ComponentProp): unknown {
  if (prop.defaultValue !== undefined) {
    const value = prop.defaultValue.trim();
    if (value === "true") return true;
    if (value === "false") return false;
    if (/^-?\d+(\.\d+)?$/.test(value)) return Number(value);
    const quoted = value.match(/^["'](.*)["']$/);
    if (quoted?.[1] !== undefined) return quoted[1];
  }
  const options = unionOptions(prop.type);
  if (options[0] !== undefined) return optionValue(options[0]);
  if (/\bboolean\b/.test(prop.type)) {
    return prop.required || /open|show|visible|active|enabled/i.test(prop.name);
  }
  if (/\bnumber\b/.test(prop.type)) {
    return /day/i.test(prop.name) ? 15 : 0;
  }
  if (/\bstring\b/.test(prop.type) || prop.type === "unknown") {
    return defaultText(prop.name);
  }
  if (prop.type.includes("[]")) return prop.required ? undefined : [];
  return undefined;
}

function controlFor(prop: ComponentProp): PreviewControl {
  const literalOptions = unionOptions(prop.type);
  const options =
    literalOptions.length > 0 ? literalOptions : semanticOptions(prop);
  const presets = complexPresets(prop);
  let kind: PreviewControl["kind"] = "json";
  if (isAction(prop)) kind = "action";
  else if (prop.name === "children") kind = "text";
  else if (options.length > 0) kind = "select";
  else if (/\bboolean\b/.test(prop.type)) kind = "boolean";
  else if (/\bnumber\b/.test(prop.type)) kind = "number";
  else if (/\bDate\b/.test(prop.type) || /date$/i.test(prop.name)) kind = "date";
  else if (
    /color|colour|background|foreground|accent/i.test(prop.name) &&
    /\bstring\b/.test(prop.type)
  ) {
    kind = "color";
  } else if (/\bstring\b/.test(prop.type) || prop.type === "unknown") {
    kind = "text";
  }
  const inferredDefault =
    kind === "action"
      ? undefined
      : prop.name === "children"
        ? defaultText(prop.name)
        : parseDefault(prop);
  const defaultValue =
    inferredDefault !== undefined
      ? inferredDefault
      : presets[0]?.value;
  return {
    name: prop.name,
    label: titleCase(prop.name),
    kind,
    type: prop.type,
    required: prop.required,
    options,
    ...(presets.length > 0 ? { presets } : {}),
    ...(defaultValue !== undefined ? { defaultValue } : {}),
  };
}

function relevantTokens(
  component: ComponentNode,
  tokens: DesignToken[],
): DesignToken[] {
  const referenced = new Set(
    component.classTokens
      .flatMap((className) => [...className.matchAll(/var\(--([^)]+)\)/g)])
      .map((match) => match[1])
      .filter((name): name is string => Boolean(name)),
  );
  const exact = tokens.filter((token) => referenced.has(token.name));
  if (exact.length >= 4) return exact.slice(0, 24);
  const semantic = tokens.filter(
    (token) =>
      token.kind === "color" ||
      token.kind === "radius" ||
      token.kind === "shadow",
  );
  return [...new Map([...exact, ...semantic].map((token) => [token.name, token])).values()]
    .slice(0, 24);
}

export function inferPreviewControls(component: ComponentNode): PreviewControl[] {
  const controls = component.props.map(controlFor);
  const names = new Set(controls.map((control) => control.name));
  for (const event of component.events) {
    const listenerName = `on${event.name
      .replace(/(^|[-_:])(\w)/g, (_, __, character: string) =>
        character.toUpperCase(),
      )}`;
    if (names.has(listenerName)) continue;
    controls.push({
      name: listenerName,
      label: `${titleCase(event.name)} Event`,
      kind: "action",
      type: event.payload ?? "event",
      required: false,
      options: [],
    });
  }
  return controls;
}

export function initialPreviewProps(
  controls: PreviewControl[],
): Record<string, unknown> {
  return Object.fromEntries(
    controls
      .filter(
        (control) =>
          control.kind !== "action" && control.defaultValue !== undefined,
      )
      .map((control) => [control.name, control.defaultValue]),
  );
}

export function buildPlaygroundContract(
  graph: ComponentGraph,
  component: ComponentNode,
  scenarios: PreviewScenario[] = [],
  styling: PreviewStyleEnvironment = {
    pipeline: "unknown",
    entryPoints: [],
    sourceRegistration: "not-applicable",
  },
  dependencies: PreviewDependencyEnvironment = {
    status: "missing",
    packageManager: "unknown",
    installCommand: "Install project dependencies",
  },
): ComponentPlaygroundContract {
  const renderable = component.framework === "vue" || component.exported;
  return {
    component,
    controls: inferPreviewControls(component),
    tokens: relevantTokens(component, graph.tokens),
    scenarios: scenarios.filter(
      (scenario) => scenario.componentId === component.id,
    ),
    styling,
    dependencies,
    renderable,
    ...(!renderable
      ? {
          renderabilityReason:
            "This React component is file-local. Extract or export it before isolated rendering.",
        }
      : {}),
  };
}
